version: "3.8" # Specify the version of docker-compose we will use

services: # Specify our services
  db_auth:
    image: postgres:14
    container_name: db_auth
    # restart: always
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=auth
      - DB_HOST=db_auth
      - DB_PORT=5432
    ports:
      - 5432:5432
  universe-auth:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    container_name: universe-auth
    depends_on:
      - db_auth
    ports:
      - 50051:50051
    command: ./run.sh
