// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: rsa.proto

package rsa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RSAClient is the client API for RSA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RSAClient interface {
	GetPublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error)
}

type rSAClient struct {
	cc grpc.ClientConnInterface
}

func NewRSAClient(cc grpc.ClientConnInterface) RSAClient {
	return &rSAClient{cc}
}

func (c *rSAClient) GetPublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	out := new(PublicKeyResponse)
	err := c.cc.Invoke(ctx, "/rsa.RSA/GetPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RSAServer is the server API for RSA service.
// All implementations must embed UnimplementedRSAServer
// for forward compatibility
type RSAServer interface {
	GetPublicKey(context.Context, *PublicKeyRequest) (*PublicKeyResponse, error)
	mustEmbedUnimplementedRSAServer()
}

// UnimplementedRSAServer must be embedded to have forward compatible implementations.
type UnimplementedRSAServer struct {
}

func (UnimplementedRSAServer) GetPublicKey(context.Context, *PublicKeyRequest) (*PublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedRSAServer) mustEmbedUnimplementedRSAServer() {}

// UnsafeRSAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RSAServer will
// result in compilation errors.
type UnsafeRSAServer interface {
	mustEmbedUnimplementedRSAServer()
}

func RegisterRSAServer(s grpc.ServiceRegistrar, srv RSAServer) {
	s.RegisterService(&RSA_ServiceDesc, srv)
}

func _RSA_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RSAServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rsa.RSA/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RSAServer).GetPublicKey(ctx, req.(*PublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RSA_ServiceDesc is the grpc.ServiceDesc for RSA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RSA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rsa.RSA",
	HandlerType: (*RSAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _RSA_GetPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rsa.proto",
}
